### ISSUE TITLE
[Future request] Move towards software keyboard

### ISSUE THREAD

**Issue by Favna** [J-D-K/JKSM#10]
Today (well.. 21 hours ago at time of posting) ctrulib has finally gotten a long awaited update which now grants us support for the official software keyboard in homebrew application (`swkbd.h` / `swkbd.c`). It would be beyond amazing of JKSM could start using this.

[Commit that adds this support](https://github.com/smealum/ctrulib/commit/bbd0fe92d3aed76098c92c01ba7845f09577c272)

**Comment by J-D-K** [comment]
Already being worked on. I'm was so happy to see it finally done. Now I can stop reworking the old one.

**Comment by J-D-K** [comment]
It works. The problem is that I was in the middle of getting the home button straightened out too, so I can't update it right away. Next release will have it and I hope it won't be long.

**Comment by abdullahbasri** [comment]
same here red screen or looking installed sd can someone help
