### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Floof2k** [J-D-K/JKSM#10]
Can't get past "Looking installed SD Titles. Sometimes gets stuck on yellow or red screen if I dont even make it to that point

**Comment by J-D-K** [comment]
This is because it doesn't work on *hax yet. I'm looking into it when I have time. It's actually very odd. I can't even get a simple, bare bones hello world to boot with a targeted title.

**Comment by DumbJoe** [comment]
Well what did you do before then that broke it? Could backtrack.....and revert the changes or even work on a separate version for *hax users.....
