### ISSUE TITLE
Save restore crash

### ISSUE THREAD

**Issue by adiktus** [J-D-K/JKSM#13]
JKSM version: 7/12 and 7/18 cia
System: N3DS US 11.7, Luma 9.1
Cart tried: MH3U

Save backup was successful, but save restore causes an arm11 exception crash.

**Comment by adiktus** [comment]
Oh, so it's not the same for all MH3U carts? Don't worry about me, I'll just use checkpoint for this specific game. But if you need any testing from me, please let me know. (Like uploading a crash dump or something)

**Comment by leonjmagnus** [comment]
Having an arm11 exception as well while trying to restore a save for the JP version of Bravely Second. Not sure how to upload crash dump either.

**Comment by J-D-K** [comment]
If anyone is having these issues, I'm curious if this version has the same issue. It has one line commented out.
[git_zip.zip](https://github.com/J-D-K/JKSM/files/2268110/git_zip.zip)

**Comment by adiktus** [comment]
Oh, it didn't crash in this version 👍

**Comment by J-D-K** [comment]
Yep. It's related to path wrapping. Gonna leave this open since it's not really fixed.

**Comment by J-D-K** [comment]
@adiktus 
It took me a while cause I've been busy, but mind giving this a shot? I rewrote the text wrapping for both versions and it _seems_ more stable.
[JKSM.zip](https://github.com/J-D-K/JKSM/files/2299583/JKSM.zip)
