### ISSUE TITLE
Can't backup if name contains specific symbols

### ISSUE THREAD

**Issue by zern78** [J-D-K/JKSM#15]
In latest release nothing happens when trying to backup if title name contains some symbols, I think.
For example - BoxBoy series have "!" at the end of title.
But if I remember correctly, previous version was able to backup and restore, at least from BoxBoy games (maybe because in path spaces and symbols were converted to underscore).

**Comment by J-D-K** [comment]
Newer versions have code to remove spaces from the end of titles and that should have fixed this.
