### ISSUE TITLE
Crash upon opening application

### ISSUE THREAD

**Issue by wartab** [J-D-K/JKSM#16]
I tried following this:
https://github.com/J-D-K/JKSM/issues/3

Still crashing
```
Title Count: 6
Attempt title 0004000002C23200: failed. No saves?
Attempt title 00040000001DEB00: failed. No saves?
Attempt title 000400000D921E00: failed. No saves?
Attempt title 000400000F800100: failed. No saves?
ID: 0004000E00022800: Skip
Attempt title 0004000000126B00: failed. No saves?
```
Crash Dump
[crash_dump_00000002.zip](https://github.com/J-D-K/JKSM/files/2280252/crash_dump_00000002.zip)

**Comment by J-D-K** [comment]
Sorry it took so long to get back to ya. Do you mind trying [this](https://github.com/J-D-K/JKSM/issues/13#issuecomment-414060882) build? A lot of these issues might be due to me getting lazy when wrapping text.
