### ISSUE TITLE
When I click titles , my 3ds freezes?

### ISSUE THREAD

**Issue by j-ar2** [J-D-K/JKSM#17]
I amtrying to use PKHex on JKSM. It seems as if it does not recognize my ultra sun game

**Comment by J-D-K** [comment]
Do you have anything digital or installed to your SD? I think I know what the problem is. I'll get back with a fix when it's done.

**Comment by J-D-K** [comment]
This fix it? All I had to do was rearrange some stuff.
[JKSM.zip](https://github.com/J-D-K/JKSM/files/2300823/JKSM.zip)
