### ISSUE TITLE
Steelhax

### ISSUE THREAD

**Issue by Birboffire** [J-D-K/JKSM#18]
When I open JKSM via homebrew (with steelhax) and I open pokemon ultra sun by clicking titles, I can't click saves. Extra saves works, but saves doesn't, and I need it to use Pkhex. Is there a version I can download? I'm on 11.8.0.41 U

**Comment by J-D-K** [comment]
[This](https://gbatemp.net/threads/release-jks-savemanager-homebrew-cia-save-manager.413143/page-177#post-8209851) is the last version I know of that can be used with hax until/if I get it straightened out.

**Comment by DumbJoe** [comment]
How did you get steelhax working on 11.8? I thought it only works up to 11.2 and lower.....

**Comment by thebelt24** [comment]
@DumbJoe I installed 11.8 using [this guide](https://www.youtube.com/watch?v=T_sQfs0u66g&t=7s). Just make sure you don't have any other old homebrew versions on your SD card.

**Comment by DumbJoe** [comment]
> 
> 
> @DumbJoe I installed 11.8 using [this guide](https://www.youtube.com/watch?v=T_sQfs0u66g&t=7s). Just make sure you don't have any other old homebrew versions on your SD card.

OH it's steel miner, from here: http://steelminer.jisagi.net/ which is a slightly different method....
