### ISSUE TITLE
Black screen on launch after building from repo (both 3dsx and cia)

### ISSUE THREAD

**Issue by dragos240** [J-D-K/JKSM#23]
Hi there,

This seems similar to the thread posted in May. A black screen on launch. I had to actually change a few files so that it would compile. On line 43 in hbfilter.cpp, you have this:
`httpcGetResponseStatusCode(&filter, &code, 0);` where it should be this: `httpcGetResponseStatusCode(&filter, &code);` The makefile also needed to be updated as it didn't link with -lcitro3d. Also I can't seem to find the code for the keyboard anywhere. Is that stored in another repo or am I just missing something? This was built with current versions of the software needed to build JKSM. A fix is appreciated.

EDIT: I see you're using  the official software keyboard now. Previously you were using your own personal keyboard code. Can I see what that looked like?

**Comment by J-D-K** [comment]
If you're using git, use this instead "git clone -b cleanup https://github.com/J-D-K/JKSM.git" and it should build with the latest libs. Unfortunately, I had a bunch of PC problems and stuff come up and wasn't able to do much until recently. I had hoped to have it merged and released by now.

**Comment by dragos240** [comment]
Thanks. It builds now. Haven't tested installing it though. I have to transfer stuff from this x86_64 Linux box to my x86 Linux box because the x86 Linux box actually runs makerom correctly. After that's done, I'll report back to see if it runs alright.

**Comment by dragos240** [comment]
It works. Is it normal for the .3dsx version to be very limited in its saving functionality? It only lets me edit "System Settings" and you can't export anything. If you try to export something it gives the error: "Error opening save archive: C920454F"

**Comment by J-D-K** [comment]
Did you copy JKSM.xml to your 3DS too? It's needed to target a title. The 3dsx and CIA work differently, because the homebrew loader doesn't have enough permissions to open save data the same way.

**Comment by dragos240** [comment]
Yeah that fixes it.
