### ISSUE TITLE
Is this currently not working with hax? When do you think it will?

### ISSUE THREAD

**Issue by Severynn99** [J-D-K/JKSM#24]
I only just managed to finally get homebrew and this is something I NEED to have. I didn't know it only worked with cfw. But hey, I'm patient enough XD

**Comment by ShinyRayquaza9** [comment]
I personally like cfw better, it's easier to access programs, It can export fine but either the new version can't import or i'm just dumb

**Comment by J-D-K** [comment]
I need to grab a new 3DS charger cause mine just stopped working. Maybe I can try looking into it this weekend.

**Comment by Severynn99** [comment]
Ah okay thank you ^^ I'll be keeping an eye on this then
