### ISSUE TITLE
Issues importing/exporting ACNL

### ISSUE THREAD

**Issue by Kayxlicious** [J-D-K/JKSM#25]
I am having issues when I select what title I want to export/import.

I dragged the folders/files onto the root of the sd.
Next, I went into Homebrew selected JKSM Save 
Selected ACNL and it freezes

Am I missing a step?

**Comment by Zetchzie** [comment]
your not using the updated acnl are you?

**Comment by Kayxlicious** [comment]
Update:

I did not install the CIA that was the issue. 
All fixed, thank you.
