### ISSUE TITLE
A title name with japanese characters screws-up whole game/app list

### ISSUE THREAD

**Issue by Robz8** [J-D-K/JKSM#26]
Whenever I have a game/app installed, with a title containing japanese characters, I have to select "Refresh Games", or else, the game/app list is screwed-up.
Can you look into this issue?

**Comment by J-D-K** [comment]
Try this instead: https://github.com/J-D-K/JKSM/blob/cleanup/JKSM.cia and get back to me if it doesn't work. I'll have to look at it again if it doesn't.

**Comment by Robz8** [comment]
Thanks! That worked.
