### ISSUE TITLE
How to Import/Export Saves?

### ISSUE THREAD

**Issue by AoDrako** [J-D-K/JKSM#26]
Recently installed CFW on my 3ds using the 11.8 Seedminer method, Installed the JKSM.3DSX file and running it was fine however it would be nice if I had some help on how to import and export a save as there doesn't seem to be a way to export my save or even import it.

**Comment by doritojesus** [comment]
When you open the JKSM with the title you want, and it brings you to the menu with the list:

save data
delete save data
extra data
delete extra data
exit

Select save data, then click new. name the save file whatever you want. then select your save, which should be under the word "new" and it will have whatever name you gave it. clicking a will export that save to the sd, and then pressing y will import the data, it might take a few tries tho

i know this is a little over the place but i hope this helps somewhat
