### ISSUE TITLE
Save Data not working

### ISSUE THREAD

**Issue by CookieLPP** [J-D-K/JKSM#27]
When I click on ,,Save Data´´ nothing happens im pressing all the buttons but nothing does anything.

**Comment by CookieLPP** [comment]
Im running Firmware Version 11.8.0-41E and im Using the Sub Wars Homebrew Method.

**Comment by CookieLPP** [comment]
I think I used Steelminer to Homebrew my Nintendo 3DS, also im trying to get my save from Pokemon Moon

**Comment by Severynn99** [comment]
Same for me. It just doesn't work yet with hax, I think?

**Comment by J-D-K** [comment]
Sorry guys, it doesn't currently. Code is there to work with *hax, but you will only be greeted with a red screen after the target selector. I've been trying to narrow it down when I have free time.

**Comment by richyrich50** [comment]
Im running Firmware Version 11.8.0-41U and im Using the Sub Wars Homebrew Method. Also not working for me.

**Comment by CookieLPP** [comment]
Yes I use the Sub Wars Method too. Tank you for looking into it I hope it works soon. :D

**Comment by badjujus** [comment]
I'm in the same boat; using the Sub Wars method and trying to save Sun and Moon (but I was unable to save a few other titles when I tried to test, like Fantasy Life and Smash). Very hopeful this will be fixed soon! Do older versions let you dump saves?

**Comment by J-D-K** [comment]
Figured I'd give an update. I'm still trying when I can. A lot has changed in the year or so when I couldn't work on the project. If I find anything, I will update you as soon as I can. 

@badjujus 
Yes, older 3dsx's still work as far as I know.

**Comment by J-D-K** [comment]
OK, it took me much longer than I thought, but I _might_ have a version that works on *hax now. No changes needed to be made to JKSM itself. I had to modify ctrulib.

**Comment by CookieLPP** [comment]
Now I can click on Titles but when I try to click on Save Data for example on Pokemon Omega Ruby, it says the archive cannot be opened. I tried it with several other titles and the same messages appears everytime.

**Comment by CookieLPP** [comment]
Extra Data however works.

**Comment by J-D-K** [comment]
If you are on steelhax you **need** the xml file and 3dsx in the same directory together on your 3DS. JKSM works differently for these. It does not have the same freedom the CIA allows and can only open what the homebrew menu targets.

**Comment by badjujus** [comment]
Works great!! Tested making and restoring saves on a few games thank you so much for getting to this man! Your work is super appreciated. :>

**Comment by stupidlogins** [comment]
You seriously think the .cia is fine? Fantasy Life still throws an error when I try and get its save, I'd very much like to not have to do 212 hours again
