### ISSUE TITLE
Should all system titles show up when i select system titles using the .cia version?

### ISSUE THREAD

**Issue by RuralOrange** [J-D-K/JKSM#29]
Whenever i select the system titles option only Activity Log, Friend List, Mii Maker, Nintendo eShop, Nitendo Network ID Settings, and System Settings shows up. Is there supposed to be more, I do select reload titles but it doesn't change anything.

**Comment by J-D-K** [comment]
Newer versions only show what can actually be opened. What are you looking for that isn't there?

**Comment by RuralOrange** [comment]
> Newer versions only show what can actually be opened. What are you looking for that isn't there?

streetpass mii plaza

**Comment by J-D-K** [comment]
[JKSM.zip](https://github.com/J-D-K/JKSM/files/2636244/JKSM.zip)
This build should reload your system titles too when you hit Reload Titles. Tell me if it shows up now, because the only other thing I can guess is that you haven't started Mii Plaza, maybe?

**Comment by RuralOrange** [comment]
> [JKSM.zip](https://github.com/J-D-K/JKSM/files/2636244/JKSM.zip)
> This build should reload your system titles too when you hit Reload Titles. Tell me if it shows up now, because the only other thing I can guess is that you haven't started Mii Plaza, maybe?

I did select the reload the titles and have played streetpass plaza, updated it and it still didnt show up. It really isnt a big deal to me if all of the system titles dont appear because I normally want saves from games.
