### ISSUE TITLE
3DS crash when opening

### ISSUE THREAD

**Issue by minkad** [J-D-K/JKSM#3]
3DS crashes when opening jksm. I have a handful of japanese games installed which may be causing the problem. THe Fault status dislayed is: Translation - Section
Current Process: JKSM

**Comment by J-D-K** [comment]
Do you mind trying to run this, and if it still crashes, checking the file 'sd:/JKSV/titlesDeb.txt'? I need to see what it's getting stuck on exactly.
<img src="https://dl.dropboxusercontent.com/s/avgteapvsvvw6wq/deb_QR.png" />

**Comment by minkad** [comment]
It works now! Thanks for the quick response and solution!
