### ISSUE TITLE
Doesn't exit to homebrew menu

### ISSUE THREAD

**Issue by pixelmasher** [J-D-K/JKSM#30]
It doesn't exit to homebrew menu. It exits to home menu. Could you fix it so it exits to homebrew menu? Some games don't work in JKSM and some don't work in CheckPoint when you try to bulk save. It makes it easier to go between the two. It could be some titles don't have a save file yet and JKSM is trying to dump the save.

**Comment by J-D-K** [comment]
What games are giving JKSM problems? I'll look into it when I can.

**Comment by pixelmasher** [comment]
I don't recall now, but I'll start to write them down. I think part of the issue maybe when bulk saving, it hangs on titles without a save file yet. Maybe you could have it ignore during bulk save if it doesn't have a save file.

**Comment by J-D-K** [comment]
This was probably because I made a hack-job ctrulib to get *hax going. I'm assuming it closes to the hbmenu now, because it does for me.
