### ISSUE TITLE
Archive can't be opened?

### ISSUE THREAD

**Issue by Severynn99** [J-D-K/JKSM#31]
I open the file I want to save and then choose 'save data' but then it tells me 'The archive cannot be opened!'
I don't know what to do. I'm using steelhax and pokemon moon. Do I need to do something else first?

**Comment by Severynn99** [comment]
Okay so my stupid mistake was that I just downloaded the wrong file. Wow. It worked when I got the right file

**Comment by bowocie** [comment]
hi i have the same problem as you but i dont kow how to fix it

**Comment by MoistBruh** [comment]
Could you explain your issue/solution in more depth? I'm having the same problem but I don't understand what the correct files are.
