### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by NinjaBoyLao** [J-D-K/JKSM#37]
I honestly don't know where else to contact you, ill close this whenever you respond. How does JKSM parse filter.txt? can i use hashtags (#) to comment out lines?

**Comment by J-D-K** [comment]
It currently just goes line by line with fgets and uses strtoul to convert the text to and unsigned int. Making it ignore a line starting with '#' wouldn't be difficult though.

**Comment by NinjaBoyLao** [comment]
okay, just trying to see if i could add lines to identify each low id in the list. lemme know if  anything changes
