### ISSUE TITLE
The Archive cannot be opened

### ISSUE THREAD

**Issue by bowocie** [J-D-K/JKSM#37]
So when i open jksm using homebrew, (im using ninjahax) i go to my pokemon ultra moon and hit Save Data, but when i select that it just says The archive cannot be opened! please help because i have been try really hard to fix this for the past few days it nothings happened. :(

**Comment by WAUthethird** [comment]
Depending on the game, sometimes save data will be stored in "Extra Data" instead. Can you try archiving the extra data of PMUM?

**Comment by bowocie** [comment]
the extra data works i can save that

**Comment by bowocie** [comment]
Nevermind I just downloaded the wrong file. Thanks anyways!
