### ISSUE TITLE
"There was an error opening the file for writing" for Professor Layon vs Phoenix Wright

### ISSUE THREAD

**Issue by NurioHin** [J-D-K/JKSM#38]
When trying to backup the save on a legitimate cartridge for Professor Layton vs Phoenix Wright (EU version), I get the following error:

![error](https://user-images.githubusercontent.com/18533703/57178663-65853080-6e74-11e9-8704-46ea31beed86.png)

Perhaps it has something to do with the title of the game. Perhaps it's the period in the title that messes with it. You can see the title in this screenshot:

![title](https://user-images.githubusercontent.com/18533703/57178676-8d749400-6e74-11e9-95fc-c70907bd0f81.png)

Note the period after "Prof". The reason I think this period might be the cause is because someone else is having the same issue with other Professor Layton games here: #19 

Another reason I think this might be the reason is because Checkpoint can backup the save without issue. And when I check the title there, it has removed the period after "Prof" and replaced it with a space instead

**Comment by NurioHin** [comment]
Okay, a little bit of an update on my speculation. Apparently it is probably not the period, since JKSM seems to parse "New Super Mario Bros. 2" just fine by removing the period there. I can only assume it does (or at least tries to) the same for "Prof. Layton"...

Then I imagine it might be the length of the title. As you can see in the screenshot above, it's being truncated (at the exact same length as Checkpoint does, in fact) as it's way too long. But maybe JKSM glitches out here when trying to write the save to the SD card whereas Checkpoint properly truncates it? And since all Professor Layton titles are so long, it only makes sense that the other Layton games suffer from the same problem as noted here: #19

**Comment by J-D-K** [comment]
Do you mind uploading the title cache from your SD card so I can check it out? I can use it to see what's up when it tries to create the directory.

**Comment by NurioHin** [comment]
I don't particularly mind, but it only holds currently installed titles, right? Meaning that my PLvsPW cartridge doesn't show up there at all (since it's a cartridge), so I don't know how much use it is

[titles.zip](https://github.com/J-D-K/JKSM/files/3153967/titles.zip)

Unless you mean something else when you mention the title cache?

**Comment by J-D-K** [comment]
Sorry, I spaced on the fact it's a cart. `````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````+
625.4`

**Comment by J-D-K** [comment]
Yeah, sorry. I glossed over the cartridge part. Use this special version of JKSM. It has an extra option to dump the cart title to `sdmc:/JKSV/cart.bin` in the main menu. Upload that and I should be able to figure it out.
[JKSM.zip](https://github.com/J-D-K/JKSM/files/3155127/JKSM.zip)

**Comment by NurioHin** [comment]
Here you go:

[cart.zip](https://github.com/J-D-K/JKSM/files/3167551/cart.zip)

I checked the file myself too and it seems to parse and truncate the title just fine, at least when dumping it to this file, though it does seem to have two spaces at the end of the title, possibly transformed from the periods at the end?

**Comment by J-D-K** [comment]
Thank you. I think I know what's happening. JKSM is replacing `.`'s with spaces, but that leaves two spaces at the end of the file safe string in this case. JKSM only handles one if I remember right, to deal with Smash. I'll get back to ya with a fix.

**Comment by NurioHin** [comment]
Do you happen to have a fix?

**Comment by NurioHin** [comment]
It's been a while. Not to sound impatient, but do you have a fix now?

**Comment by J-D-K** [comment]
I apologize. I have been very busy lately. Here, I attempted to write a quick fix for ya, but I don't have any games to test it with. Let me know if it works for you. I added a function that _should_ trim spaces from the end of safe title strings. Reload your titles to be 100% sure it took effect.
[JKSM.zip](https://github.com/J-D-K/JKSM/files/3307972/JKSM.zip)

**Comment by trlkly** [comment]
The  CIA in the zip file worked for me. I was able to export and then import the saves from Prof. Layton vs. Phoenix Wright.

I imported my completed save file, and thus was able to get access to the extra content.

**Comment by TheShadowRunner** [comment]
Any chance to make that special build an official release?

**Comment by J-D-K** [comment]
Latest build contains the code that fixes this.
