### ISSUE TITLE
Rebuild/new release?

### ISSUE THREAD

**Issue by tcby45** [J-D-K/JKSM#40]
I've tried to build the most recent commit (e1d89bf) & dependencies on a Linux machine, but it keeps erroring for some reason. Can you please re-build the 3dsx/cia in the repo and/or make a new release?

**Comment by Committee** [comment]
Wouldn't this suffice?:

https://github.com/J-D-K/JKSM/blob/master/JKSM.cia

**Comment by tcby45** [comment]
Normally, yes, but the current commit that applies to that CIA is outdated; the latest commit contains a new set of filters that would be useful.

**Comment by J-D-K** [comment]
The filter.txt file is external, on the SD card, and read on start up so I don't have to update the whole CIA to update the filtered titles. It can be downloaded from within the program itself.

**Comment by tcby45** [comment]
Ah, understood. Thanks!
