### ISSUE TITLE
Unable to exit JKSM without turning 3DS off

### ISSUE THREAD

**Issue by h0lley** [J-D-K/JKSM#41]
on 3DS firmware 11.10.0-43E, when exiting JKSM I am just getting a permanent red screen on the touch screen, and black on top screen.

This happens when selecting "Exit" from the menu or when pressing Start as well.

**Comment by drjenza** [comment]
This is also happening to me but with the newest update. Is it affecting your saves in any way?

**Comment by h0lley** [comment]
no worries, backing up and restoring saves still works fine for me, it's just that every time you are done using the tool you have to hard-turn-off by holding the power button...

**Comment by J-D-K** [comment]
I'll see what I can do soon. I had to make a hack-job ctrulib to get it working under *hax, but I think I'm just going to drop *hax now. It's too much trouble now.

**Comment by h0lley** [comment]
I should have probably also mentioned that the entry point I am using Steel Diver: Sub Wars.
perhaps drjenza is using the same and the issue is only occurring then?

**Comment by drjenza** [comment]
I am using steel diver: sub wars. Mainly because this method seems to be
the only one that works with the newest 3ds update.

**Comment by J-D-K** [comment]
*hax support has been dropped. It's too outdated and touchy now. Sorry.
