### ISSUE TITLE
Importing Issue

### ISSUE THREAD

**Issue by Pyrrite** [J-D-K/JKSM#47]
When I try to import a Tomodachi Life save from the JKSM folder it doesn't let me even open it, no matter how many times I press the A button and I didn't get any types of errors. The same thing happened when I tried to get the save from a different folder. I then copied the save to the root of my SD card and it let me click on it, but when I copied to save and opened Tomodachi Life the save I imported wasn't the one that appeared in the game. Instead it was the save I had previous to exporting my save to JKSM to get edited. I don't know if this is an issue with JKSM or with the save editor I used but there's clearly sonething wrong.

**Comment by J-D-K** [comment]
Y is the import button. Am I misunderstanding something? Kinda confused to be honest.
