### ISSUE TITLE
Pokemon deleted, Help!

### ISSUE THREAD

**Issue by icyigor** [J-D-K/JKSM#53]
Hello, i was using PKSM to transfer my pokemon from omega ruby to moon, i quit the extrastorage and left PKSM but forgot to save! When i check back all the pokemon that I transfered are gone! There not in the game, there not in the extra storage, I even check my omega ruby and there not there, is there anyway to recover them? Like data mining or going into the files. Thanks!

**Comment by TheMCNerd2017** [comment]
This is the wrong project, dude. JKSM is a general save file and extra data manager, and is way different than PKSM. Search up PKSM on github and you should be able to find the correct area to ask for help.

For your issue, you have to restore from a backup of your ORAS save file. If you don't have one, then you are unfortunately out of luck.
