### ISSUE TITLE
crashing when clicking titles JKSM 05.08.2020

### ISSUE THREAD

**Issue by PlinixS** [J-D-K/JKSM#56]
it was working before i decided to uninstall the cfw than after reinstalling it. it started doing it i tried older versions and it just keeps doing it idk what i did wrong

**Comment by J-D-K** [comment]
Do you have any games installed that have saves? That's what I assume would be causing it. My menus never handled being empty good. I keep forgetting to fix it.

**Comment by PlinixS** [comment]
Nope it just crashes :( idk what i did wrong bc it worked last time and i feel xd

**Comment by PlinixS** [comment]
I have got it fixed i just had to reload titles we are good to go thanmyou sorry if i bothered u :)

**Comment by J-D-K** [comment]
Ok. Sorry I disappeared. I'm spread really thin and trying not to get burned out.

**Comment by PlinixS** [comment]
> Ok. Sorry I disappeared. I'm spread really thin and trying not to get burned out. 

Ur fine i wasnt expecting an instant reply. I was gonna figure it out sometime when ever i get bord and figure it out on the 3ds. I understand but thankyou :). And im sorry im allways busy to woth work and shit i got into. ur not alone 😔
