### ISSUE TITLE
3dsx for rosalina needed

### ISSUE THREAD

**Issue by bonboncat** [J-D-K/JKSM#57]
Since there's a huge update in luma rosalina we can now run homebrew app without being detected in activity log.
It would be nice to have jksm.3dsx that supported by rosalina homebrew launcher in the future to keep out 3ds clean.
I have test latest release of jksm and it's not working with rosalina homebrew launcher.
my luma version is 8.0
b9s version 1.2
firmware 11.4
thank you so much for creating jksm, the best save manager i love and use.

**Comment by CodeBrain-** [comment]
For now you can do the following to use JKSM as a homebrew app (CIA does not need to follow this process)

1. Enter JKSM's folder and delete the JKSM.xml file (This tells the homebrew channel it needs to target a game to function first)'
2. Load the game you want to dump/inject the save file on
3. Enter Rosalina, replace the game with the homebrew channel in the miscellaneous settings
4. Exit the game and re-enter to get into the Homebrew Channel
5. Load JKSM. If the game is supported it will correctly load the save file and allow you to dump/inject it.

If this process doesn't work, the game is probably using extdata to make a save file (Like MH Generations). The limitations are a slightly longer execution to do save extraction/injections, while also needing to completely reboot your 3DS once you have finished using JKSM for you to be able to play the game again. 

Method discovered by Phalk on GBAtemp.

**Comment by bonboncat** [comment]
Ah it works. Thank you. But i'm missing that play coin set XD
