### ISSUE TITLE
How To Link?

### ISSUE THREAD

**Issue by gsugambit** [J-D-K/JKSM#69]
The old JKSM had a how to on where to put files and everything. I can't find it on this github is there something I am missing or some other link I should have?

**Comment by SmackBro** [comment]
What do you mean? you just install the .cia with FBI or you put the .3dsx in your "3ds" folder and then start homebrew,if you backup saves,JKSM will automaticly create new directories SD/JKSV/Saves (etc.) where you can find your saves.
