### ISSUE TITLE
Save Data isn't working

### ISSUE THREAD

**Issue by floopkyra** [J-D-K/JKSM#7]
I'm currently only using the JKSM to hack for Animal Crossing New Leaf, and possibly a few pokemon games. But when I select the Save Data option, nothing happens. It works fine for the deleting saved data, but not for exporting and/or importing save data. Did an update happen? It seems like it's changed. Please reply as soon as you can, thanks in advance!

**Comment by floopkyra** [comment]
I'm also using the freakyhax open point, btw, but all of that works fine.

**Comment by jacobk999** [comment]
I have this same problem using the newest build

**Comment by jacobk999** [comment]
Oh wait sorry I didn't read the issue down below that you must cfw to export saves and inport. BTW will exporting and importing becoming for non CFW users
